"""empty message

Revision ID: 21224a6ee77c
Revises: 9756024d98f4
Create Date: 2019-08-26 14:50:07.305275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21224a6ee77c'
down_revision = '9756024d98f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_use', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_use')
    # ### end Alembic commands ###
